let tela = document.querySelector('.screen');
let numerosESinais = document.querySelectorAll('.numerosESinais');
let igual = document.querySelector('.igual');
let reset = document.querySelector('.reset');
let del = document.querySelector('.del');

for (let i = 0; i < numerosESinais.length; i++) {
    
    let valor = numerosESinais[i];
    
    
    valor.onclick = function () {
        var inserir = tela.innerHTML;
        tela.innerHTML = inserir + numerosESinais[i].value;
    }

    del.onclick = function () {
        let apagar = tela.innerHTML;
        tela.innerHTML = apagar.substring(0, apagar.length -1);
    }

    reset.onclick = function () {
        let limpar = tela.innerHTML;
        tela.innerHTML = limpar.substring(limpar.length);
    }

    igual.onclick = function () {
        let resultado = tela.innerHTML;
        if(resultado){
            tela.innerHTML = eval(resultado);
        }
    }
}

let temas = document.querySelectorAll('.temas');
console.log(temas);

temas[0].onclick = function () {
    document.querySelector('body').style.backgroundColor = 'hsl(222, 26%, 31%)';
    document.getElementById('temas1').style.backgroundColor = 'hsl(225, 21%, 49%)';
    document.getElementById('temas2').style.backgroundColor = 'hsl(225, 21%, 49%)';
    document.getElementById('temas3').style.backgroundColor = 'hsl(225, 21%, 49%)';
    document.getElementById('temas1').style.color = '#FFF';
    document.getElementById('temas2').style.color = '#FFF';
    document.getElementById('temas3').style.color = '#FFF';
    document.querySelector('p').style.color = '#FFF';
    document.querySelector('h1').style.color = '#FFF';
    document.getElementById('divScreen').style.backgroundColor = 'hsl(224, 36%, 15%)';
    document.getElementById('screen').style.color = '#FFF';
    document.getElementById('botoes').style.backgroundColor = 'hsl(223, 31%, 20%)';
    document.getElementById('numerosESinais1').style.backgroundColor = 'hsl(30, 25%, 89%)';
    document.getElementById('numerosESinais1').style.color = 'hsl(225, 21%, 49%)';
    document.getElementById('numerosESinais1').style.boxShadow = '0 4px hsl(28, 16%, 65%)';
    document.getElementById('numerosESinais2').style.backgroundColor = 'hsl(30, 25%, 89%)';
    document.getElementById('numerosESinais2').style.color = 'hsl(225, 21%, 49%)';
    document.getElementById('numerosESinais2').style.boxShadow = '0 4px hsl(28, 16%, 65%)';
    document.getElementById('numerosESinais3').style.backgroundColor = 'hsl(30, 25%, 89%)';
    document.getElementById('numerosESinais3').style.color = 'hsl(225, 21%, 49%)';
    document.getElementById('numerosESinais3').style.boxShadow = '0 4px hsl(28, 16%, 65%)';
    document.getElementById('numerosESinais4').style.backgroundColor = 'hsl(30, 25%, 89%)';
    document.getElementById('numerosESinais4').style.color = 'hsl(225, 21%, 49%)';
    document.getElementById('numerosESinais4').style.boxShadow = '0 4px hsl(28, 16%, 65%)';
    document.getElementById('numerosESinais5').style.backgroundColor = 'hsl(30, 25%, 89%)';
    document.getElementById('numerosESinais5').style.color = 'hsl(225, 21%, 49%)';
    document.getElementById('numerosESinais5').style.boxShadow = '0 4px hsl(28, 16%, 65%)';
    document.getElementById('numerosESinais6').style.backgroundColor = 'hsl(30, 25%, 89%)';
    document.getElementById('numerosESinais6').style.color = 'hsl(225, 21%, 49%)';
    document.getElementById('numerosESinais6').style.boxShadow = '0 4px hsl(28, 16%, 65%)';
    document.getElementById('numerosESinais7').style.backgroundColor = 'hsl(30, 25%, 89%)';
    document.getElementById('numerosESinais7').style.color = 'hsl(225, 21%, 49%)';
    document.getElementById('numerosESinais7').style.boxShadow = '0 4px hsl(28, 16%, 65%)';
    document.getElementById('numerosESinais8').style.backgroundColor = 'hsl(30, 25%, 89%)';
    document.getElementById('numerosESinais8').style.color = 'hsl(225, 21%, 49%)';
    document.getElementById('numerosESinais8').style.boxShadow = '0 4px hsl(28, 16%, 65%)';
    document.getElementById('numerosESinais9').style.backgroundColor = 'hsl(30, 25%, 89%)';
    document.getElementById('numerosESinais9').style.color = 'hsl(225, 21%, 49%)';
    document.getElementById('numerosESinais9').style.boxShadow = '0 4px hsl(28, 16%, 65%)';
    document.getElementById('numerosESinais0').style.backgroundColor = 'hsl(30, 25%, 89%)';
    document.getElementById('numerosESinais0').style.color = 'hsl(225, 21%, 49%)';
    document.getElementById('numerosESinais0').style.boxShadow = '0 4px hsl(28, 16%, 65%)';
    document.getElementById('numerosESinais+').style.backgroundColor = 'hsl(30, 25%, 89%)';
    document.getElementById('numerosESinais+').style.color = 'hsl(225, 21%, 49%)';
    document.getElementById('numerosESinais+').style.boxShadow = '0 4px hsl(28, 16%, 65%)';
    document.getElementById('numerosESinais-').style.backgroundColor = 'hsl(30, 25%, 89%)';
    document.getElementById('numerosESinais-').style.color = 'hsl(225, 21%, 49%)';
    document.getElementById('numerosESinais-').style.boxShadow = '0 4px hsl(28, 16%, 65%)';
    document.getElementById('numerosESinais*').style.backgroundColor = 'hsl(30, 25%, 89%)';
    document.getElementById('numerosESinais*').style.color = 'hsl(225, 21%, 49%)';
    document.getElementById('numerosESinais*').style.boxShadow = '0 4px hsl(28, 16%, 65%)';
    document.getElementById('numerosESinais/').style.backgroundColor = 'hsl(30, 25%, 89%)';
    document.getElementById('numerosESinais/').style.color = 'hsl(225, 21%, 49%)';
    document.getElementById('numerosESinais/').style.boxShadow = '0 4px hsl(28, 16%, 65%)';
    document.getElementById('numerosESinais.').style.backgroundColor = 'hsl(30, 25%, 89%)';
    document.getElementById('numerosESinais.').style.color = 'hsl(225, 21%, 49%)';
    document.getElementById('numerosESinais.').style.boxShadow = '0 4px hsl(28, 16%, 65%)';
    document.getElementById('del').style.backgroundColor = 'hsl(225, 21%, 49%)';
    document.getElementById('del').style.boxShadow = '0 4px hsl(224, 28%, 35%)';
    document.getElementById('reset').style.backgroundColor = 'hsl(225, 21%, 49%)';
    document.getElementById('reset').style.boxShadow = '0 4px hsl(224, 28%, 35%)';
    document.getElementById('igual').style.backgroundColor = 'hsl(6, 63%, 50%)';
    document.getElementById('igual').style.color = '#FFF';
    document.getElementById('igual').style.boxShadow = '0 4px hsl(6, 70%, 34%)';
}

temas[1].onclick = function () {
    document.querySelector('body').style.backgroundColor = 'hsl(0, 0%, 90%)';
    document.getElementById('temas1').style.backgroundColor = 'hsl(0, 5%, 81%)';
    document.getElementById('temas2').style.backgroundColor = 'hsl(0, 5%, 81%)';
    document.getElementById('temas3').style.backgroundColor = 'hsl(0, 5%, 81%)';
    document.getElementById('temas1').style.color = 'hsl(60, 10%, 19%)';
    document.getElementById('temas2').style.color = 'hsl(60, 10%, 19%)';
    document.getElementById('temas3').style.color = 'hsl(60, 10%, 19%)';
    document.querySelector('p').style.color = 'hsl(60, 10%, 19%)';
    document.querySelector('h1').style.color = 'hsl(60, 10%, 19%)';
    document.getElementById('divScreen').style.backgroundColor = 'hsl(0, 0%, 93%)';
    document.getElementById('screen').style.color = 'hsl(60, 10%, 19%)';
    document.getElementById('botoes').style.backgroundColor = 'hsl(0, 5%, 81%)';
    document.getElementById('numerosESinais1').style.backgroundColor = 'hsl(45, 7%, 89%)';
    document.getElementById('numerosESinais1').style.color = 'hsl(60, 10%, 19%)';
    document.getElementById('numerosESinais1').style.boxShadow = '0 4px hsl(35, 11%, 61%)';
    document.getElementById('numerosESinais2').style.backgroundColor = 'hsl(45, 7%, 89%)';
    document.getElementById('numerosESinais2').style.color = 'hsl(60, 10%, 19%)';
    document.getElementById('numerosESinais2').style.boxShadow = '0 4px hsl(35, 11%, 61%)';
    document.getElementById('numerosESinais3').style.backgroundColor = 'hsl(45, 7%, 89%)';
    document.getElementById('numerosESinais3').style.color = 'hsl(60, 10%, 19%)';
    document.getElementById('numerosESinais3').style.boxShadow = '0 4px hsl(35, 11%, 61%)';
    document.getElementById('numerosESinais4').style.backgroundColor = 'hsl(45, 7%, 89%)';
    document.getElementById('numerosESinais4').style.color = 'hsl(60, 10%, 19%)';
    document.getElementById('numerosESinais4').style.boxShadow = '0 4px hsl(35, 11%, 61%)';
    document.getElementById('numerosESinais5').style.backgroundColor = 'hsl(45, 7%, 89%)';
    document.getElementById('numerosESinais5').style.color = 'hsl(60, 10%, 19%)';
    document.getElementById('numerosESinais5').style.boxShadow = '0 4px hsl(35, 11%, 61%)';
    document.getElementById('numerosESinais6').style.backgroundColor = 'hsl(45, 7%, 89%)';
    document.getElementById('numerosESinais6').style.color = 'hsl(60, 10%, 19%)';
    document.getElementById('numerosESinais6').style.boxShadow = '0 4px hsl(35, 11%, 61%)';
    document.getElementById('numerosESinais7').style.backgroundColor = 'hsl(45, 7%, 89%)';
    document.getElementById('numerosESinais7').style.color = 'hsl(60, 10%, 19%)';
    document.getElementById('numerosESinais7').style.boxShadow = '0 4px hsl(35, 11%, 61%)';
    document.getElementById('numerosESinais8').style.backgroundColor = 'hsl(45, 7%, 89%)';
    document.getElementById('numerosESinais8').style.color = 'hsl(60, 10%, 19%)';
    document.getElementById('numerosESinais8').style.boxShadow = '0 4px hsl(35, 11%, 61%)';
    document.getElementById('numerosESinais9').style.backgroundColor = 'hsl(45, 7%, 89%)';
    document.getElementById('numerosESinais9').style.color = 'hsl(60, 10%, 19%)';
    document.getElementById('numerosESinais9').style.boxShadow = '0 4px hsl(35, 11%, 61%)';
    document.getElementById('numerosESinais0').style.backgroundColor = 'hsl(45, 7%, 89%)';
    document.getElementById('numerosESinais0').style.color = 'hsl(60, 10%, 19%)';
    document.getElementById('numerosESinais0').style.boxShadow = '0 4px hsl(35, 11%, 61%)';
    document.getElementById('numerosESinais+').style.backgroundColor = 'hsl(45, 7%, 89%)';
    document.getElementById('numerosESinais+').style.color = 'hsl(60, 10%, 19%)';
    document.getElementById('numerosESinais+').style.boxShadow = '0 4px hsl(35, 11%, 61%)';
    document.getElementById('numerosESinais-').style.backgroundColor = 'hsl(45, 7%, 89%)';
    document.getElementById('numerosESinais-').style.color = 'hsl(60, 10%, 19%)';
    document.getElementById('numerosESinais-').style.boxShadow = '0 4px hsl(35, 11%, 61%)';
    document.getElementById('numerosESinais*').style.backgroundColor = 'hsl(45, 7%, 89%)';
    document.getElementById('numerosESinais*').style.color = 'hsl(60, 10%, 19%)';
    document.getElementById('numerosESinais*').style.boxShadow = '0 4px hsl(35, 11%, 61%)';
    document.getElementById('numerosESinais/').style.backgroundColor = 'hsl(45, 7%, 89%)';
    document.getElementById('numerosESinais/').style.color = 'hsl(60, 10%, 19%)';
    document.getElementById('numerosESinais/').style.boxShadow = '0 4px hsl(35, 11%, 61%)';
    document.getElementById('numerosESinais.').style.backgroundColor = 'hsl(45, 7%, 89%)';
    document.getElementById('numerosESinais.').style.color = 'hsl(60, 10%, 19%)';
    document.getElementById('numerosESinais.').style.boxShadow = '0 4px hsl(35, 11%, 61%)';
    document.getElementById('del').style.backgroundColor = 'hsl(185, 42%, 37%)';
    document.getElementById('del').style.boxShadow = '0 4px hsl(185, 58%, 25%)';
    document.getElementById('reset').style.backgroundColor = 'hsl(185, 42%, 37%)';
    document.getElementById('reset').style.boxShadow = '0 4px hsl(185, 58%, 25%)';
    document.getElementById('igual').style.backgroundColor = 'hsl(25, 98%, 40%)';
    document.getElementById('igual').style.color = '#FFF';
    document.getElementById('igual').style.boxShadow = '0 4px hsl(25, 99%, 27%)';
}

temas[2].onclick = function () {
    document.querySelector('body').style.backgroundColor = 'hsl(268, 75%, 9%)';
    document.getElementById('temas1').style.backgroundColor = 'hsl(268, 71%, 12%)';
    document.getElementById('temas2').style.backgroundColor = 'hsl(268, 71%, 12%)';
    document.getElementById('temas3').style.backgroundColor = 'hsl(268, 71%, 12%)';
    document.getElementById('temas1').style.color = 'hsl(52, 100%, 62%)';
    document.getElementById('temas2').style.color = 'hsl(52, 100%, 62%)';
    document.getElementById('temas3').style.color = 'hsl(52, 100%, 62%)';
    document.querySelector('p').style.color = 'hsl(52, 100%, 62%)';
    document.querySelector('h1').style.color = 'hsl(52, 100%, 62%)';
    document.getElementById('divScreen').style.backgroundColor = 'hsl(268, 71%, 12%)';
    document.getElementById('screen').style.color = 'hsl(52, 100%, 62%)';
    document.getElementById('botoes').style.backgroundColor = 'hsl(268, 71%, 12%)';
    document.getElementById('numerosESinais1').style.backgroundColor = 'hsl(268, 47%, 21%)';
    document.getElementById('numerosESinais1').style.color = 'hsl(52, 100%, 62%)';
    document.getElementById('numerosESinais1').style.boxShadow = '0 4px hsl(290, 70%, 36%)';
    document.getElementById('numerosESinais2').style.backgroundColor = 'hsl(268, 47%, 21%)';
    document.getElementById('numerosESinais2').style.color = 'hsl(52, 100%, 62%)';
    document.getElementById('numerosESinais2').style.boxShadow = '0 4px hsl(290, 70%, 36%)';
    document.getElementById('numerosESinais3').style.backgroundColor = 'hsl(268, 47%, 21%)';
    document.getElementById('numerosESinais3').style.color = 'hsl(52, 100%, 62%)';
    document.getElementById('numerosESinais3').style.boxShadow = '0 4px hsl(290, 70%, 36%)';
    document.getElementById('numerosESinais4').style.backgroundColor = 'hsl(268, 47%, 21%)';
    document.getElementById('numerosESinais4').style.color = 'hsl(52, 100%, 62%)';
    document.getElementById('numerosESinais4').style.boxShadow = '0 4px hsl(290, 70%, 36%)';
    document.getElementById('numerosESinais5').style.backgroundColor = 'hsl(268, 47%, 21%)';
    document.getElementById('numerosESinais5').style.color = 'hsl(52, 100%, 62%)';
    document.getElementById('numerosESinais5').style.boxShadow = '0 4px hsl(290, 70%, 36%)';
    document.getElementById('numerosESinais6').style.backgroundColor = 'hsl(268, 47%, 21%)';
    document.getElementById('numerosESinais6').style.color = 'hsl(52, 100%, 62%)';
    document.getElementById('numerosESinais6').style.boxShadow = '0 4px hsl(290, 70%, 36%)';
    document.getElementById('numerosESinais7').style.backgroundColor = 'hsl(268, 47%, 21%)';
    document.getElementById('numerosESinais7').style.color = 'hsl(52, 100%, 62%)';
    document.getElementById('numerosESinais7').style.boxShadow = '0 4px hsl(290, 70%, 36%)';
    document.getElementById('numerosESinais8').style.backgroundColor = 'hsl(268, 47%, 21%)';
    document.getElementById('numerosESinais8').style.color = 'hsl(52, 100%, 62%)';
    document.getElementById('numerosESinais8').style.boxShadow = '0 4px hsl(290, 70%, 36%)';
    document.getElementById('numerosESinais9').style.backgroundColor = 'hsl(268, 47%, 21%)';
    document.getElementById('numerosESinais9').style.color = 'hsl(52, 100%, 62%)';
    document.getElementById('numerosESinais9').style.boxShadow = '0 4px hsl(290, 70%, 36%)';
    document.getElementById('numerosESinais0').style.backgroundColor = 'hsl(268, 47%, 21%)';
    document.getElementById('numerosESinais0').style.color = 'hsl(52, 100%, 62%)';
    document.getElementById('numerosESinais0').style.boxShadow = '0 4px hsl(290, 70%, 36%)';
    document.getElementById('numerosESinais+').style.backgroundColor = 'hsl(268, 47%, 21%)';
    document.getElementById('numerosESinais+').style.color = 'hsl(52, 100%, 62%)';
    document.getElementById('numerosESinais+').style.boxShadow = '0 4px hsl(290, 70%, 36%)';
    document.getElementById('numerosESinais-').style.backgroundColor = 'hsl(268, 47%, 21%)';
    document.getElementById('numerosESinais-').style.color = 'hsl(52, 100%, 62%)';
    document.getElementById('numerosESinais-').style.boxShadow = '0 4px hsl(290, 70%, 36%)';
    document.getElementById('numerosESinais*').style.backgroundColor = 'hsl(268, 47%, 21%)';
    document.getElementById('numerosESinais*').style.color = 'hsl(52, 100%, 62%)';
    document.getElementById('numerosESinais*').style.boxShadow = '0 4px hsl(290, 70%, 36%)';
    document.getElementById('numerosESinais/').style.backgroundColor = 'hsl(268, 47%, 21%)';
    document.getElementById('numerosESinais/').style.color = 'hsl(52, 100%, 62%)';
    document.getElementById('numerosESinais/').style.boxShadow = '0 4px hsl(290, 70%, 36%)';
    document.getElementById('numerosESinais.').style.backgroundColor = 'hsl(268, 47%, 21%)';
    document.getElementById('numerosESinais.').style.color = 'hsl(52, 100%, 62%)';
    document.getElementById('numerosESinais.').style.boxShadow = '0 4px hsl(290, 70%, 36%)';
    document.getElementById('del').style.backgroundColor = 'hsl(281, 89%, 26%)';
    document.getElementById('del').style.boxShadow = '0 4px hsl(285, 91%, 52%)';
    document.getElementById('reset').style.backgroundColor = 'hsl(281, 89%, 26%)';
    document.getElementById('reset').style.boxShadow = '0 4px hsl(285, 91%, 52%)';
    document.getElementById('igual').style.backgroundColor = 'hsl(176, 100%, 44%)';
    document.getElementById('igual').style.color = '#000';
    document.getElementById('igual').style.boxShadow = '0 4px hsl(177, 92%, 70%)';
}
